#create new patient entity
POST localhost:4000/patients
Content-Type: application/json

{
  "name" : "Sameera test",
  "email": "sameera_test8@gmail.com",
  "address": "123 diyatalawa",
  "dateOfBirth": "2000-04-07",
  "registeredDate": "2025-08-20"
}